apiVersion: v1
kind: PersistentVolume
metadata:
  name: ucm-pv-volume-producer
  namespace: uc3-applications
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ucmdemo"