apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ucm-pv-claim
  namespace: uc3-applications
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi