apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${ClaimName}
  namespace: ${ApplicationName}
spec:
  storageClassName: ${ClaimSpecStorage}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi